name: Deploy App to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Show Port
        run: echo ${{ secrets.VPS_PORT }}

      - name: Set up environment variables
        run: |
          echo "VITE_PUBLIC_URL=${{ secrets.VITE_PUBLIC_URL }}" >> $GITHUB_ENV
          echo "VITE_API_URL_PROD=${{ secrets.VITE_API_URL_PROD }}" >> $GITHUB_ENV
          echo "VITE_API_URL_DEV=${{ secrets.VITE_API_URL_DEV }}" >> $GITHUB_ENV
          echo "VITE_POSTHOG_KEY=${{ secrets.VITE_POSTHOG_KEY }}" >> $GITHUB_ENV
          echo "VITE_POSTHOG_HOST=${{ secrets.VITE_POSTHOG_HOST }}" >> $GITHUB_ENV
          echo "VITE_ENV=${{ secrets.VITE_ENV }}" >> $GITHUB_ENV
          echo "VITE_MINIO_URL=${{ secrets.VITE_MINIO_URL }}" >> $GITHUB_ENV
          echo "VITE_MINIO_ENDPOINT=${{ secrets.VITE_MINIO_ENDPOINT }}" >> $GITHUB_ENV
          echo "VITE_MINIO_ACCESSKEY=${{ secrets.VITE_MINIO_ACCESSKEY }}" >> $GITHUB_ENV
          echo "VITE_MINIO_SECRETKEY=${{ secrets.VITE_MINIO_SECRETKEY }}" >> $GITHUB_ENV
          echo "VITE_MINIO_USESSL=${{ secrets.VITE_MINIO_USESSL }}" >> $GITHUB_ENV

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: dist/
          target: /var/www/app.metromedics.co/html/
